package com.spacesim.ship;

import java.util.Objects;

/**
 * Deterministic Stage-17.5F energetic shield runtime.
 *
 * <p>A shield is a finite energy/power/heat system. Coverage is geometric, absorption is bounded by
 * both field reserve and interaction power, recharge consumes an explicitly granted electrical
 * power budget, and emitter integrity can only reduce field capability.</p>
 */
public final class ShieldFieldRuntime {
    private static final double TWO_PI = Math.PI * 2d;
    private static final double EPSILON = 1e-9d;

    /**
     * Physical fitted shield definition.
     *
     * @param mountId physical emitter mount
     * @param reserveCapacityJ maximum field reserve
     * @param interactionPowerW maximum instantaneous threat interaction power
     * @param rechargePowerW maximum electrical recharge draw
     * @param rechargeEfficiency fraction of granted recharge energy stored in the field
     * @param heatPerAbsorbedJ waste heat generated per absorbed threat joule
     * @param restartDelaySeconds collapse lockout before recharge/restart
     * @param coverageCenterRad hull-local coverage center angle
     * @param coverageHalfArcRad half width of the covered angular sector
     */
    public record Definition(
            String mountId,
            double reserveCapacityJ,
            double interactionPowerW,
            double rechargePowerW,
            double rechargeEfficiency,
            double heatPerAbsorbedJ,
            double restartDelaySeconds,
            double coverageCenterRad,
            double coverageHalfArcRad) {
        // Compact-constructor validation; record-level Javadoc owns the public parameter contract.
        public Definition {
            if (mountId == null || mountId.isBlank()) {
                throw new IllegalArgumentException("mountId must be non-blank");
            }
            requirePositive(reserveCapacityJ, "reserveCapacityJ");
            requirePositive(interactionPowerW, "interactionPowerW");
            requireNonNegative(rechargePowerW, "rechargePowerW");
            requireUnitInterval(rechargeEfficiency, "rechargeEfficiency");
            requireNonNegative(heatPerAbsorbedJ, "heatPerAbsorbedJ");
            requireNonNegative(restartDelaySeconds, "restartDelaySeconds");
            requireFinite(coverageCenterRad, "coverageCenterRad");
            if (!Double.isFinite(coverageHalfArcRad) || coverageHalfArcRad <= 0d || coverageHalfArcRad > Math.PI) {
                throw new IllegalArgumentException("coverageHalfArcRad must be in (0,pi]");
            }
        }
    }

    /**
     * Persistent shield field state.
     *
     * @param reserveJ current stored field energy
     * @param accumulatedHeatJ heat generated by shield interactions/recharge bookkeeping
     * @param collapsed whether the field currently cannot interact with threats
     * @param restartRemainingSeconds remaining collapse lockout
     * @param emitterIntegrity physical emitter integrity in [0,1]
     */
    public record State(
            double reserveJ,
            double accumulatedHeatJ,
            boolean collapsed,
            double restartRemainingSeconds,
            double emitterIntegrity) {
        // Compact-constructor validation; record-level Javadoc owns the public parameter contract.
        public State {
            requireNonNegative(reserveJ, "reserveJ");
            requireNonNegative(accumulatedHeatJ, "accumulatedHeatJ");
            requireNonNegative(restartRemainingSeconds, "restartRemainingSeconds");
            requireUnitInterval(emitterIntegrity, "emitterIntegrity");
        }

        /**
         * Creates a fully charged healthy field.
         *
         * @param definition fitted definition
         * @return ready state
         */
        public static State charged(Definition definition) {
            Definition checked = Objects.requireNonNull(definition, "definition");
            return new State(checked.reserveCapacityJ(), 0d, false, 0d, 1d);
        }
    }

    /**
     * Result of one threat/field interaction.
     *
     * @param state updated shield state
     * @param absorbedEnergyJ threat energy absorbed by the field
     * @param residualEnergyJ threat energy continuing to material protection
     * @param generatedHeatJ heat generated by this interaction
     * @param covered whether the threat direction intersected emitter coverage
     */
    public record Interaction(
            State state,
            double absorbedEnergyJ,
            double residualEnergyJ,
            double generatedHeatJ,
            boolean covered) { }

    /**
     * Applies one threat energy packet over an explicit interaction duration.
     *
     * @param definition fitted shield definition
     * @param state current shield state
     * @param incomingEnergyJ incoming threat energy
     * @param threatDirectionRad hull-local incoming direction
     * @param interactionSeconds positive interaction duration
     * @return deterministic interaction result
     */
    public Interaction interact(
            Definition definition,
            State state,
            double incomingEnergyJ,
            double threatDirectionRad,
            double interactionSeconds) {
        Definition checkedDefinition = Objects.requireNonNull(definition, "definition");
        State checkedState = Objects.requireNonNull(state, "state");
        requireNonNegative(incomingEnergyJ, "incomingEnergyJ");
        requireFinite(threatDirectionRad, "threatDirectionRad");
        requirePositive(interactionSeconds, "interactionSeconds");

        boolean covered = covers(checkedDefinition, threatDirectionRad);
        if (!covered || checkedState.collapsed() || checkedState.emitterIntegrity() <= 0d || incomingEnergyJ <= 0d) {
            return new Interaction(checkedState, 0d, incomingEnergyJ, 0d, covered);
        }

        double integrity = checkedState.emitterIntegrity();
        double effectiveReserveCapacityJ = checkedDefinition.reserveCapacityJ() * integrity;
        double usableReserveJ = Math.min(checkedState.reserveJ(), effectiveReserveCapacityJ);
        double interactionLimitJ = checkedDefinition.interactionPowerW() * integrity * interactionSeconds;
        double absorbedJ = Math.min(incomingEnergyJ, Math.min(usableReserveJ, interactionLimitJ));
        double residualJ = incomingEnergyJ - absorbedJ;
        double reserveJ = Math.max(0d, usableReserveJ - absorbedJ);
        double heatJ = absorbedJ * checkedDefinition.heatPerAbsorbedJ();
        boolean collapsed = reserveJ <= EPSILON && absorbedJ > 0d;
        double restart = collapsed ? checkedDefinition.restartDelaySeconds() : checkedState.restartRemainingSeconds();
        State updated = new State(
                reserveJ,
                checkedState.accumulatedHeatJ() + heatJ,
                collapsed,
                restart,
                integrity);
        return new Interaction(updated, absorbedJ, residualJ, heatJ, covered);
    }

    /**
     * Advances recharge/restart using power explicitly granted by the common engineering power layer.
     *
     * @param definition fitted definition
     * @param state current state
     * @param deltaSeconds positive simulation interval
     * @param grantedRechargePowerW non-negative power actually granted to this shield
     * @return advanced state
     */
    public State step(
            Definition definition,
            State state,
            double deltaSeconds,
            double grantedRechargePowerW) {
        Definition checkedDefinition = Objects.requireNonNull(definition, "definition");
        State checkedState = Objects.requireNonNull(state, "state");
        requirePositive(deltaSeconds, "deltaSeconds");
        requireNonNegative(grantedRechargePowerW, "grantedRechargePowerW");
        double integrity = checkedState.emitterIntegrity();
        double restart = Math.max(0d, checkedState.restartRemainingSeconds() - deltaSeconds);
        boolean locked = checkedState.collapsed() && restart > 0d;
        if (locked || integrity <= 0d) {
            return new State(
                    Math.min(checkedState.reserveJ(), checkedDefinition.reserveCapacityJ() * integrity),
                    checkedState.accumulatedHeatJ(),
                    checkedState.collapsed(),
                    restart,
                    integrity);
        }

        double acceptedPowerW = Math.min(grantedRechargePowerW, checkedDefinition.rechargePowerW() * integrity);
        double storedJ = acceptedPowerW * checkedDefinition.rechargeEfficiency() * deltaSeconds;
        double capacityJ = checkedDefinition.reserveCapacityJ() * integrity;
        double reserveJ = Math.min(capacityJ, checkedState.reserveJ() + storedJ);
        boolean collapsed = reserveJ <= EPSILON;
        return new State(reserveJ, checkedState.accumulatedHeatJ(), collapsed, 0d, integrity);
    }

    /**
     * Applies physical emitter damage without granting energy/capability.
     *
     * @param definition fitted definition
     * @param state current state
     * @param integrity new emitter integrity in [0,1]
     * @return capacity-clamped damaged state
     */
    public State withEmitterIntegrity(Definition definition, State state, double integrity) {
        Definition checkedDefinition = Objects.requireNonNull(definition, "definition");
        State checkedState = Objects.requireNonNull(state, "state");
        requireUnitInterval(integrity, "integrity");
        double reserve = Math.min(checkedState.reserveJ(), checkedDefinition.reserveCapacityJ() * integrity);
        boolean collapsed = checkedState.collapsed() || integrity <= 0d || reserve <= EPSILON;
        double restart = collapsed
                ? Math.max(checkedState.restartRemainingSeconds(), checkedDefinition.restartDelaySeconds())
                : checkedState.restartRemainingSeconds();
        return new State(reserve, checkedState.accumulatedHeatJ(), collapsed, restart, integrity);
    }

    private static boolean covers(Definition definition, double directionRad) {
        double difference = normalize(directionRad - definition.coverageCenterRad());
        return Math.abs(difference) <= definition.coverageHalfArcRad() + EPSILON;
    }

    private static double normalize(double angle) {
        double result = angle % TWO_PI;
        if (result > Math.PI) {
            result -= TWO_PI;
        } else if (result < -Math.PI) {
            result += TWO_PI;
        }
        return result;
    }

    private static void requirePositive(double value, String field) {
        if (!Double.isFinite(value) || value <= 0d) {
            throw new IllegalArgumentException(field + " must be finite and positive");
        }
    }

    private static void requireNonNegative(double value, String field) {
        if (!Double.isFinite(value) || value < 0d) {
            throw new IllegalArgumentException(field + " must be finite and non-negative");
        }
    }

    private static void requireFinite(double value, String field) {
        if (!Double.isFinite(value)) {
            throw new IllegalArgumentException(field + " must be finite");
        }
    }

    private static void requireUnitInterval(double value, String field) {
        if (!Double.isFinite(value) || value < 0d || value > 1d) {
            throw new IllegalArgumentException(field + " must be in [0,1]");
        }
    }
}
